serverList:
    - http://megan-pi-iot.cfapps.io/index.html
    - http://katie-pi-iot.cfapps.io/index.html
    - http://david-pi-iot.cfapps.io/index.html
    - http://jpf-flask-pi-iot.cfapps.io/index.html
    - http://shane-pi-iot.cfapps.io/index.html